### ISSUE TITLE
Boards.h hardware abstraction for the esp32

### ISSUE THREAD

**Issue by DanNduati** [Gustavo053/firmata-esp32#1]
Trying to run this on my esp32 dev board spits out the  following
```
In file included from /home/daniel/Arduino/libraries/ConfigurableFirmata/src/ConfigurableFirmata.h:18:0,
                 from /home/daniel/Arduino/esp32_firmata/esp32_firmata.ino:7:
/home/daniel/Arduino/libraries/ConfigurableFirmata/src/utility/Boards.h:711:2: error: #error "Please edit Boards.h with a hardware abstraction for this board"
 #error "Please edit Boards.h with a hardware abstraction for this board"
  ^
```
I'm not quite sure what the problem might be because i assume the board definitions come automatically defined on installation of the esp32 Arduino core

**Comment by Gustavo053** [comment]
Hello, Dan! 

Did you unzip the ConfigurableFirmata folder inside the libraries folder and verified the board connected as esp32 dev module?

Try this following steps:
• Unzip the ConfigurableFirmata folder inside the libraries folder;
• Make sure the board connected is esp32 dev module;
• Upload testesp32.ino file on board (if you prefer, put the testesp32.ino file folder inside libraries -> Firmata -> examples).

**Comment by DanNduati** [comment]
Hello Gustavo thanks for the response.
